### ISSUE TITLE
Can't Build Project. Can't resolve the reference 'System.IntPtr ObjCRuntime.DisposableObject::get_Handle()'

### ISSUE THREAD

**Issue by KwasiVT** [xamarin-bindings-for-twilio/TwilioVideoXamarinIOS#7]
Hi, I install the nuget package but when I went to build I received this error:

Can't resolve the reference 'System.IntPtr ObjCRuntime.DisposableObject::get_Handle()', referenced from the method 'System.Boolean Twilio.Video.iOS.TVIAudioDeviceCapturerWrapper::StartCapturing(System.IntPtr)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'

Did incorrectly import the package?

**Comment by mhender24** [comment]
Any update on this?  Running into same issue.

**Comment by mhender24** [comment]
I ran into this issue as well, any solution?

**Comment by KwasiVT** [comment]
Bump

**Comment by jtorvald** [comment]
@KwasiVT @mhender24 I just updated to the latest version and I don't experience issues. Is this on debug build or a linked release build?

**Comment by jtorvald** [comment]
In my release build I have this in my additional monotouch parameters: `--linkskip=Twilio.Video.iOS`. Maybe that helps. Or try the parameters in the readme.

**Comment by mhender24** [comment]
Sorry for the delay.  This worked for me.  Thanks.
